backend:
  name: github
  repo: ifjso/helloworld

publish_mode: editorial_workflow
media_folder: static/assets
public_folder: /assets

collections:
  - name: about-me
    label: About Me
    folder: contents/about-me
    create: true
    fields:
      - { name: path, label: Path }
      - {
          name: type,
          label: Type,
          widget: select,
          options: ['about-me', 'work-experience'],
          default: 'about-me',
        }
      - { name: created_at, label: Created At, widget: datetime }
      - { name: name, label: Name }
      - { name: intro, label: Introduction }
      - { name: tech_stack, label: Tech Stack }
      - { name: body, label: Body, widget: markdown }

  - name: work-experience
    label: Work Experience
    folder: contents/work-experience
    create: true
    fields:
      - { name: path, label: Path }
      - {
          name: type,
          label: Type,
          widget: select,
          options: ['about-me', 'work-experience'],
          default: 'work-experience',
        }
      - { name: created_at, label: Created At, widget: datetime }
      - { name: name, label: Name }
      - { name: company, label: Company }
      - { name: position, label: Position }
      - {
          name: task,
          label: Task,
          widget: select,
          options: ['백엔드', '프론트엔드'],
          default: '백엔드',
        }
      - { name: started_at, label: Started At, widget: date }
      - { name: ended_at, label: Ended At, widget: date }
      - {
          name: base_tech,
          label: Base Tech,
          widget: select,
          options: ['SpringBoot', 'Node.js', 'React'],
          default: 'SpringBoot',
        }
      - { name: tech_stack, label: Tech Stack }
      - { name: body, label: Body, widget: markdown }
