backend:
  name: github
  repo: ifjso/helloworld

publish_mode: editorial_workflow
media_folder: static/assets
public_folder: /assets

collections:
  - name: about-me
    label: About Me
    folder: contents/about-me
    create: true
    fields:
      - { name: type, label: Type }
      - { name: date, label: Date, widget: datetime }
      - { name: name, label: Name }
      - { name: intro, label: Introduction }
      - { name: tech-stack, label: Tech Stack }
      - { name: body, label: Body, widget: markdown }

  - name: work-experience
    label: Work Experience
    folder: contents/work-experience
    create: true
    fields:
      - { name: type, label: Type }
      - { name: date, label: Date, widget: datetime }
      - { name: name, label: Name }
      - { name: description, label: Description }
      - { name: company, label: Company }
      - { name: position, label: Position }
      - { name: period, label: Period }
      - { name: tech-stack, label: Tech Stack }
      - { name: body, label: Body, widget: markdown }
