backend:
  name: github
  repo: ifjso/helloworld

publish_mode: editorial_workflow
media_folder: static/assets
public_folder: /assets

collections:
  - name: about-me
    label: About Me
    folder: contents/about-me
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: name, label: Name }
      - { name: intro, label: Introduction }
      - { name: tech-stack, label: Tech Stack }
      - { name: body, label: Body, widget: markdown }

  - name: blog
    label: Blog
    folder: contents/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
